### ISSUE TITLE
error: replication controller "dummy-2" has failed progressing

### ISSUE THREAD

**Issue by kenuenoibm** [openshift-labs/learn-katacoda#478] opened 2019-05-30 06:31 UTC
Hello.
I am working on the scenario "Transferring Files in and out of Containers" and having an issue on Step 5 of 5.

I ran "oc set volume dc/dummy --add --name=tmp-mount --claim-name=data --type pvc --claim-size=1G --mount-path /mnt"
and then ran "oc rollout status dc/dummy".
I got the following message when I ran it first time.
"$ oc rollout status dc/dummy
Waiting for rollout to finish: 1 old replicas are pending termination...

Then, I waited for a while and tried it again.

$ oc rollout status dc/dummy
error: replication controller "dummy-2" has failed progressing
$

I also ran the following command.
$ oc get pvc
NAME      STATUS    VOLUME    CAPACITY   ACCESSMODES   STORAGECLASS   AGE
data      Pending                                                     12m
$

Could you please help me on this issue?

**Comment by nanoamp** [comment] 2019-11-13 14:26
I don't think anyone is interested, but I have the same thing today, and it looks to be due to the persistent storage not linking up. From the web UI's _Storage_ section, under _Events_:

```
Failed binding
no persistent volumes available for this claim and no storage class is set
142 times in the last 40 minutes
```

If there's no storage available for the tutorial clusters to claim from, for some reason, then it's not going to work.

**Comment by BenHall** [comment] 2019-11-13 15:33
Thanks for the feedback! We're currently working on upgrading this to 4.2 which will hopefully resolve the issue.

**Comment by jdob** [comment] 2021-06-21 18:41
@cedricclyburn please verify this one along with #1169

**Comment by cedricclyburn** [comment] 2021-06-25 01:03
With #1169 merged, looks like the issue is fixed! Thank you for the report!

**Closed by cedricclyburn** 2021-06-25 01:03 UTC
