### ISSUE TITLE
Building s2i with Thoth Advise - Deyploment fails => nvcc not found

### ISSUE THREAD

**Issue by troppens** [openshift-labs/learn-katacoda#866] opened 2020-08-28 20:20 UTC
I am trying the "Building s2i with Thoth Advise" module:
https://learn.openshift.com/ai-machine-learning/thoth-s2i-advise/

The application fails to deploy with an exception:
`nvcc: command not found`

I tried multiple times rebuilding the learning environment, so the issue seems to persist.

Here is the full output:

```
Your Interactive Learning Environment Bash Terminal

$ launch.sh
OpenShift Ready
OpenShift Ready
$ oc whoami
admin
$ oc new-project myproject
Now using project "myproject" on server "https://openshift:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app django-psql-example

to build a new example application in Python. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node

$ oc process -f https://raw.githubusercontent.com/thoth-station/s2i-example/log-thoth/openshift.yaml | oc apply -f -
buildconfig.build.openshift.io/s2i-example-log created
deploymentconfig.apps.openshift.io/s2i-example-log created
imagestream.image.openshift.io/s2i-example-log created
imagestream.image.openshift.io/s2i-thoth-ubi8-py36 created
$ oc logs bc/s2i-example-log -f
Cloning "https://github.com/thoth-station/s2i-example" ...
        Commit: 39e81d211a75ab5577b13f8f9cdf7b83183571e1 (Merge pull request #25 from saisankargochhayat/log-thoth)
        Author: Saisankar Gochhayat <saisankargochhayat@gmail.com>
        Date:   Tue Mar 31 11:46:23 2020 -0400
Caching blobs under "/var/cache/blobs".
Getting image source signatures
Copying blob sha256:47db82df7f3f4393c1f19c362a2db2c47ca049b6fb20bef041dfc9bdb12a4504
Copying blob sha256:6cc5487eb078291c64e0539c6d57546606b3936b71eabc7eec7960d069927ba4
Copying blob sha256:77c58f19bd6e67185938abb6bbb6ec229e07a5e607453904294d982de141d2f0
Copying blob sha256:d5e8f7f1544a0b24f6a422173079f16930b1b17b81e57cdeeb07f53a9629a4de
Copying blob sha256:27502e318cbd58f1f9cb317719f4b7cdc46d9a114dd8e49bd12220970e669d79
Copying blob sha256:71391dc11a78542160544b68e45bc123ff55a2e84aeb6fa99b672d75765bc2f8
Copying blob sha256:afd7930aabf0f9629c10e7d442f03f8801994e069fd583c817171980273c05e3
Copying config sha256:7a259598d3aadea06e9cb324c535a88a899d79e4393f2998435212ee1698fc31
Writing manifest to image destination
Storing signatures
Generating dockerfile with builder image quay.io/thoth-station/s2i-thoth-ubi8-py36@sha256:8405255092ed8ea6aab321a52f511b4e8a8d80fff8bc1c4dc6d29b6a09b37789
STEP 1: FROM quay.io/thoth-station/s2i-thoth-ubi8-py36@sha256:8405255092ed8ea6aab321a52f511b4e8a8d80fff8bc1c4dc6d29b6a09b37789
STEP 2: LABEL "io.openshift.build.commit.id"="39e81d211a75ab5577b13f8f9cdf7b83183571e1" "io.openshift.build.commit.ref"="log-thoth" "io.openshift.build.commit.message"="Merge pull request #25 from saisankargochhayat/log-thoth" "io.openshift.build.source-location"="https://github.com/thoth-station/s2i-example" "io.openshift.build.image"="quay.io/thoth-station/s2i-thoth-ubi8-py36@sha256:8405255092ed8ea6aab321a52f511b4e8a8d80fff8bc1c4dc6d29b6a09b37789" "io.openshift.build.commit.author"="Saisankar Gochhayat <saisankargochhayat@gmail.com>" "io.openshift.build.commit.date"="Tue Mar 31 11:46:23 2020 -0400"
STEP 3: ENV OPENSHIFT_BUILD_NAME="s2i-example-log-1" OPENSHIFT_BUILD_NAMESPACE="myproject" OPENSHIFT_BUILD_SOURCE="https://github.com/thoth-station/s2i-example" OPENSHIFT_BUILD_REFERENCE="log-thoth" OPENSHIFT_BUILD_COMMIT="39e81d211a75ab5577b13f8f9cdf7b83183571e1" ENABLE_PIPENV="1" THOTH_ADVISE="1" THOTH_PROVENANCE_CHECK="0" THOTH_DRY_RUN="0" THAMOS_CONFIG_TEMPLATE="thoth_conf_template.yaml" THAMOS_CONFIG_EXPAND_ENV="1" THAMOS_FORCE="1" THAMOS_VERBOSE="1" THAMOS_DEBUG="0" THOTH_HOST="api.moc.thoth-station.ninja" THOTH_FROM_MASTER="0"THOTH_ERROR_FALLBACK="1" THAMOS_DEV="0"
STEP 4: USER root
STEP 5: COPY upload/src /tmp/src
STEP 6: RUN chown -R 1001:0 /tmp/src
time="2020-08-28T19:54:55Z" level=warning msg="pkg/chroot: error unmounting \"/tmp/buildah652246882/mnt/rootfs\": error checking if \"/tmp/buildah652246882/mnt/rootfs/sys/fs/cgroup/devices\" is mounted: no such file or directory"
time="2020-08-28T19:54:55Z" level=warning msg="pkg/bind: error unmounting \"/tmp/buildah652246882/mnt/rootfs\": error checking if \"/tmp/buildah652246882/mnt/rootfs/sys/fs/cgroup/devices\" is mounted: no such file or directory"
STEP 7: USER 1001
STEP 8: RUN /usr/libexec/s2i/assemble
/tmp/src ~
>>> Thoth s2i builder image version: 0.15.1
>>> Performing hardware and software discovery...
2020-08-28 19:54:57,759 [319] DEBUG    thamos: Debug mode turned on
2020-08-28 19:54:57,759 [319] DEBUG    thamos: Thamos version: '0.11.1'
2020-08-28 19:54:57,762 [319] INFO     thamos: Creating configuration file from a configuration template 'thoth_conf_template.yaml'
2020-08-28 19:54:57,762 [319] DEBUG    thamos.config: Reading configuration from 'thoth_conf_template.yaml'
2020-08-28 19:54:57,762 [319] INFO     thamos.config: Discovering host runtime environment
2020-08-28 19:54:57,763 [319] INFO     thamos.discover: Detected CPU: cpu_family: 23, cpu_model: 49, cpu_model_name: AMD EPYC 7502P 32-Core Processor
2020-08-28 19:54:57,770 [319] INFO     thamos.discover: No CUDA version detected
2020-08-28 19:54:57,770 [319] DEBUG    thamos.discover: Unable to detect CUDA version - nvcc returned non-zero version: {'stdout': '','stderr': '/bin/sh: nvcc: command not found\n', 'return_code': 127, 'command': 'nvcc --version', 'timeout': 60, 'message': '<thoth.analyzer.command.CommandResult object at 0x7f1d4e707908>'}
2020-08-28 19:54:57,784 [319] CRITICAL root: Traceback (most recent call last):
  File "/usr/local/bin/thamos", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/thamos/cli.py", line 580, in config
    configuration.create_default_config(template)
  File "/usr/local/lib/python3.6/site-packages/thamos/config.py", line 170, in create_default_config
    **(os.environ.__dict__ if expand_env else {}),
KeyError: 'THOTH_HOST'

subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 1
$
```

**Comment by troppens** [comment] 2020-08-29 09:20
Same issue with the next modules: _Building s2i with Thoth Provenance_.

Here is the debug information:
```
Debug Information

Content Version: 94a164e7a3f2c5539338f8e54137d9102bf767bb

Last Updated: 2020-08-27T15:55:37.590Z

Connected - Katacoda Host: simba07 in europe

host0 IP: 172.17.0.14
client1 IP: 172.17.0.15
```

**Comment by btannous** [comment] 2020-09-03 20:51
@4n4nd @hemajv @saisankargochhayat @tmckayus 
Do you mind taking a look at this?  Thank you!

**Comment by saisankargochhayat** [comment] 2020-09-03 21:47
Thanks for reporting, we will look into it.

**Comment by fridex** [comment] 2020-09-04 11:37
@troppens could you please check if the issue is still relevant for the v0.16.1 of Thoth s2i images?

**Comment by troppens** [comment] 2020-09-04 15:01
@fridex - Thanks for looking into this issue. I have re-done this learning module. In between it reads:
```
>>> Thoth advises are not activated
```

I cannot tell, if this is expected or a bug, because I am a newbie here. Here is the full output. 

```
$ oc process -f https://raw.githubusercontent.com/thoth-station/s2i-example/log-thoth/openshift.yaml | oc apply -f -
buildconfig.build.openshift.io/s2i-example-log created
deploymentconfig.apps.openshift.io/s2i-example-log created
imagestream.image.openshift.io/s2i-example-log created
imagestream.image.openshift.io/s2i-thoth-ubi8-py36 created
$ oc logs bc/s2i-example-log -f
Cloning "https://github.com/thoth-station/s2i-example" ...
        Commit: 39e81d211a75ab5577b13f8f9cdf7b83183571e1 (Merge pull request #25 from saisankargochhayat/log-thoth)
        Author: Saisankar Gochhayat <saisankargochhayat@gmail.com>
        Date:   Tue Mar 31 11:46:23 2020 -0400
Caching blobs under "/var/cache/blobs".
Getting image source signatures
Copying blob sha256:47db82df7f3f4393c1f19c362a2db2c47ca049b6fb20bef041dfc9bdb12a4504
Copying blob sha256:77c58f19bd6e67185938abb6bbb6ec229e07a5e607453904294d982de141d2f0
Copying blob sha256:d5e8f7f1544a0b24f6a422173079f16930b1b17b81e57cdeeb07f53a9629a4de
Copying blob sha256:71391dc11a78542160544b68e45bc123ff55a2e84aeb6fa99b672d75765bc2f8
Copying blob sha256:7d9f44d99dc4c7ed4f405c42d4ae635a1c21ee2eae55061e1065137c9c40d9d7
Copying blob sha256:6cc5487eb078291c64e0539c6d57546606b3936b71eabc7eec7960d069927ba4
Copying blob sha256:5d903aef382f2b74467abad3436796b8a7d7301c65c015da2135ac4ae49ecb18
Copying config sha256:a5c120390660a3d1de9b25dd5b52f723149779f56c7393cb6eb1ed7eef6c1751
Writing manifest to image destination
Storing signatures
Generating dockerfile with builder image quay.io/thoth-station/s2i-thoth-ubi8-py36@sha256:2ddd90b0bcdf5b605854caeac91c99fae97459e121dd73871669d7c29b3a0493
STEP 1: FROM quay.io/thoth-station/s2i-thoth-ubi8-py36@sha256:2ddd90b0bcdf5b605854caeac91c99fae97459e121dd73871669d7c29b3a0493
STEP 2: LABEL "io.openshift.build.image"="quay.io/thoth-station/s2i-thoth-ubi8-py36@sha256:2ddd90b0bcdf5b605854caeac91c99fae97459e121dd73871669d7c29b3a0493" "io.openshift.build.commit.author"="Saisankar Gochhayat <saisankargochhayat@gmail.com>" "io.openshift.build.commit.date"="Tue Mar 31 11:46:23 2020 -0400" "io.openshift.build.commit.id"="39e81d211a75ab5577b13f8f9cdf7b83183571e1" "io.openshift.build.commit.ref"="log-thoth" "io.openshift.build.commit.message"="Merge pull request #25 from saisankargochhayat/log-thoth" "io.openshift.build.source-location"="https://github.com/thoth-station/s2i-example"
STEP 3: ENV OPENSHIFT_BUILD_NAME="s2i-example-log-1" OPENSHIFT_BUILD_NAMESPACE="myproject" OPENSHIFT_BUILD_SOURCE="https://github.com/thoth-station/s2i-example" OPENSHIFT_BUILD_REFERENCE="log-thoth" OPENSHIFT_BUILD_COMMIT="39e81d211a75ab5577b13f8f9cdf7b83183571e1" ENABLE_PIPENV="1" THOTH_ADVISE="1" THOTH_PROVENANCE_CHECK="0" THOTH_DRY_RUN="0" THAMOS_CONFIG_TEMPLATE="thoth_conf_template.yaml" THAMOS_CONFIG_EXPAND_ENV="1" THAMOS_FORCE="1" THAMOS_VERBOSE="1" THAMOS_DEBUG="0" THOTH_HOST="api.moc.thoth-station.ninja" THOTH_FROM_MASTER="0"THOTH_ERROR_FALLBACK="1" THAMOS_DEV="0"
STEP 4: USER root
STEP 5: COPY upload/src /tmp/src
STEP 6: RUN chown -R 1001:0 /tmp/src
time="2020-09-04T14:44:47Z" level=warning msg="pkg/chroot: error unmounting \"/tmp/buildah818725919/mnt/rootfs\": error checking if \"/tmp/buildah818725919/mnt/rootfs/sys/fs/cgroup/cpuset\" is mounted: no such file or directory"
time="2020-09-04T14:44:47Z" level=warning msg="pkg/bind: error unmounting \"/tmp/buildah818725919/mnt/rootfs\": error checking if \"/tmp/buildah818725919/mnt/rootfs/sys/fs/cgroup/cpuset\" is mounted: no such file or directory"
STEP 7: USER 1001
STEP 8: RUN /usr/libexec/s2i/assemble
/tmp/src ~
>>> Thoth s2i builder image version: 0.16.1
>>> Performing hardware and software discovery...
2020-09-04 14:44:52,162 [320] DEBUG    thamos: Debug mode turned on
2020-09-04 14:44:52,162 [320] DEBUG    thamos: Thamos version: '0.12.1'
2020-09-04 14:44:52,163 [320] INFO     thamos: Creating configuration file from a configuration template 'thoth_conf_template.yaml'
2020-09-04 14:44:52,164 [320] DEBUG    thamos.config: Reading configuration from 'thoth_conf_template.yaml'
2020-09-04 14:44:52,164 [320] INFO     thamos.config: Discovering host runtime environment
2020-09-04 14:44:52,164 [320] INFO     thamos.discover: Detected CPU: cpu_family: 6, cpu_model: 79, cpu_model_name: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
2020-09-04 14:44:52,173 [320] INFO     thamos.discover: No CUDA version detected
2020-09-04 14:44:52,174 [320] DEBUG    thamos.discover: Unable to detect CUDA version - nvcc returned non-zero version: {'stdout': '','stderr': '/bin/sh: nvcc: command not found\n', 'return_code': 127, 'command': 'nvcc --version', 'timeout': 60, 'message': '<thoth.analyzer.command.CommandResult object at 0x7f00dc253cc0>'}
2020-09-04 14:44:52,191 [320] DEBUG    thamos.config: Writing configuration file to '/tmp/src/.thoth.yaml'
>>> Thoth's configuration file after hardware and software discovery:
{
  "host": "api.moc.thoth-station.ninja",
  "tls_verify": false,
  "requirements_format": "pipenv",
  "runtime_environments": [
    {
      "name": "rhel:8.2",
      "operating_system": {
        "name": "rhel",
        "version": "8"
      },
      "hardware": {
        "cpu_family": 6,
        "cpu_model": 79
      },
      "python_version": "3.6",
      "recommendation_type": "LATEST"
    }
  ]
}
>>> Asking Thoth for advise...
2020-09-04 14:44:53,968 [329] DEBUG    thamos: Debug mode turned on
2020-09-04 14:44:53,968 [329] DEBUG    thamos: Thamos version: '0.12.1'
2020-09-04 14:44:53,970 [329] INFO     thamos.config: Expanding configuration file based on environment variables
2020-09-04 14:44:53,974 [329] INFO     thamos.config: Expanding configuration file based on environment variables
2020-09-04 14:44:53,977 [329] WARNING  thamos.config: TLS verification turned off, its highly recommended to use a secured connection,see configuration file for configuration options
2020-09-04 14:44:54,455 [329] ERROR    thamos.config: Thoth service at 'https://api.moc.thoth-station.ninja/api/v1' is unavailable (HTTP 503)
2020-09-04 14:44:54,459 [329] CRITICAL root: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/thamos/config.py", line 279, in api_discovery
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.moc.thoth-station.ninja/api/v1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/thamos", line 33, in <module>
    sys.exit(load_entry_point('thamos==0.12.1', 'console_scripts', 'thamos')())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/thamos/cli.py", line 385, in advise
    dev=dev,
  File "/usr/local/lib/python3.6/site-packages/thamos/lib.py", line 86, in wrapper
    thoth_config.api_discovery(host)
  File "/usr/local/lib/python3.6/site-packages/thamos/config.py", line 286, in api_discovery
    ) from exc
thamos.exceptions.NoApiSupported: Server does not support API v1 required by Thamos client

>>> Thoth stack analysis failed with the following log:
2020-09-04 14:44:57,685 [333] DEBUG    thamos: Debug mode turned on
2020-09-04 14:44:57,685 [333] DEBUG    thamos: Thamos version: '0.12.1'
2020-09-04 14:44:57,688 [333] INFO     thamos.config: Expanding configuration file based on environment variables
2020-09-04 14:44:57,696 [333] WARNING  thamos.config: TLS verification turned off, its highly recommended to use a secured connection,see configuration file for configuration options
2020-09-04 14:44:58,099 [333] ERROR    thamos.config: Thoth service at 'https://api.moc.thoth-station.ninja/api/v1' is unavailable (HTTP 503)
2020-09-04 14:44:58,101 [333] CRITICAL root: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/thamos/config.py", line 279, in api_discovery
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.moc.thoth-station.ninja/api/v1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/thamos", line 33, in <module>
    sys.exit(load_entry_point('thamos==0.12.1', 'console_scripts', 'thamos')())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/thamos/cli.py", line 512, in log
    log_str = get_log()
  File "/usr/local/lib/python3.6/site-packages/thamos/lib.py", line 86, in wrapper
    thoth_config.api_discovery(host)
  File "/usr/local/lib/python3.6/site-packages/thamos/config.py", line 286, in api_discovery
    ) from exc
thamos.exceptions.NoApiSupported: Server does not support API v1 required by Thamos client

>>> Restoring previous requirements lock
>>> Thoth advises are not activated
~
---> Installing application source ...
---> Upgrading pip to version 19.3.1 ...
Collecting pip==19.3.1
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-19.3.1
You are using pip version 19.3.1, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
---> Installing dependencies via micropipenv ...
---------------------------------- Pipfile.lock ----------------------------------
{
    "_meta": {
        "hash": {
            "sha256": "2f354eaddecf43134b8d5a1609be109224aa91a1bfa02eb661d752046ed64bac"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi-org",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "daiquiri": {
            "hashes": [
                "sha256:0d5bf9c5719fbca4928dc2a882c165cd2b5c81be28f7f1626ced04c1c6b4aae2",
                "sha256:236183ba51f35f4ae0e23fd20119d0fa082995c08d77bd562dbc00ea8f504bf6"
            ],
            "index": "pypi-org",
            "version": "==2.1.1"
        },
        "python-json-logger": {
            "hashes": [
                "sha256:b7a31162f2a01965a5efb94453ce69230ed208468b0bbc7fdfc56e6d8df2e281"
            ],
            "version": "==0.1.11"
        }
    },
    "develop": {}
}
---------------------------------- Pipfile.lock ----------------------------------
Collecting daiquiri==2.1.1
  Downloading https://files.pythonhosted.org/packages/75/6d/cb2a5e4f5c29f65381b646e3209ff75a409937757cb0183c7d939863d218/daiquiri-2.1.1-py2.py3-none-any.whl
Installing collected packages: daiquiri
Successfully installed daiquiri-2.1.1
Collecting python-json-logger==0.1.11
  Downloading https://files.pythonhosted.org/packages/80/9d/1c3393a6067716e04e6fcef95104c8426d262b4adaf18d7aa2470eab028d/python-json-logger-0.1.11.tar.gz
Building wheels for collected packages: python-json-logger
  Building wheel for python-json-logger (setup.py): started
  Building wheel for python-json-logger (setup.py): finished with status 'done'
  Created wheel for python-json-logger: filename=python_json_logger-0.1.11-py2.py3-none-any.whl size=4204 sha256=742fbb71f9259a17723259729359e560998d865961644f7fe18aebd3e0cfb3f4
  Stored in directory: /tmp/pip-ephem-wheel-cache-7zris8v3/wheels/97/f7/a1/752e22bb30c1cfe38194ea0070a5c66e76ef4d06ad0c7dc401
Successfully built python-json-logger
Installing collected packages: python-json-logger
Successfully installed python-json-logger-0.1.11
time="2020-09-04T14:45:06Z" level=warning msg="pkg/chroot: error unmounting \"/tmp/buildah182326632/mnt/rootfs\": error checking if \"/tmp/buildah182326632/mnt/rootfs/sys/fs/cgroup/cpuset\" is mounted: no such file or directory"
time="2020-09-04T14:45:06Z" level=warning msg="pkg/bind: error unmounting \"/tmp/buildah182326632/mnt/rootfs\": error checking if \"/tmp/buildah182326632/mnt/rootfs/sys/fs/cgroup/cpuset\" is mounted: no such file or directory"
STEP 9: CMD /usr/libexec/s2i/run
STEP 10: COMMIT temp.builder.openshift.io/myproject/s2i-example-log-1:2c322a80
Getting image source signatures
Copying blob sha256:226bfaae015f1d5712cfced3b5b628206618eaacf72f4a44d0e4084071996319
Copying blob sha256:70056249a0e202adae10aa45fef56ac4cc6497619767753515022bc9c1278251
Copying blob sha256:0bfe5b62a1ad05827328d7629f8a9a7e16642fd14f40070a395fcd16917eb4f7
Copying blob sha256:7fbe9fcfa2da3fadd05c2e7caabc3da06c1a7fc36c14f5b6dddedc5ffb42be11
Copying blob sha256:8c900de07a065f34599cd82ea05865e55fce903a0e490baf855355f64e4cb241
Copying blob sha256:1ac144a53cfc0606cd9a5d2c14779443a3f934e1d4ae4f486741beeb244fa0d9
Copying blob sha256:0c7d9cc1c3ac0078e7d2489e80a3613f3444d65a1652304516b67cb3ab1046d6
Copying blob sha256:2faebe5121141c48137d5571c3b997be013434d0fe762669b901771b8a81bc39
Copying config sha256:fad11cbb523e99012d36c215888024c35392b30544a69b8d2f84e0ce71754bdd
Writing manifest to image destination
Storing signatures
fad11cbb523e99012d36c215888024c35392b30544a69b8d2f84e0ce71754bdd

Pushing image image-registry.openshift-image-registry.svc:5000/myproject/s2i-example-log:latest ...
Getting image source signatures
Copying blob sha256:7d9f44d99dc4c7ed4f405c42d4ae635a1c21ee2eae55061e1065137c9c40d9d7
Copying blob sha256:47db82df7f3f4393c1f19c362a2db2c47ca049b6fb20bef041dfc9bdb12a4504
Copying blob sha256:77c58f19bd6e67185938abb6bbb6ec229e07a5e607453904294d982de141d2f0
Copying blob sha256:6cc5487eb078291c64e0539c6d57546606b3936b71eabc7eec7960d069927ba4
Copying blob sha256:71391dc11a78542160544b68e45bc123ff55a2e84aeb6fa99b672d75765bc2f8
Copying blob sha256:d5e8f7f1544a0b24f6a422173079f16930b1b17b81e57cdeeb07f53a9629a4de
Copying blob sha256:5d903aef382f2b74467abad3436796b8a7d7301c65c015da2135ac4ae49ecb18
Copying blob sha256:2faebe5121141c48137d5571c3b997be013434d0fe762669b901771b8a81bc39
Copying config sha256:fad11cbb523e99012d36c215888024c35392b30544a69b8d2f84e0ce71754bdd
Writing manifest to image destination
Storing signatures
Successfully pushed image-registry.openshift-image-registry.svc:5000/myproject/s2i-example-log@sha256:500cb158a17404243e4d91531efc6bf712f89745381c484215988e7f6c2b58ee
Push successful
$ oc logs -f dc/s2i-example-log
--> Scaling s2i-example-log-1 to 1
--> Success
$ oc logs -f dc/s2i-example-log
2020-09-04 14:45:31,465 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:45:41,468 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:45:51,480 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:46:01,484 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:46:11,494 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:46:21,504 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:46:31,514 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:46:41,524 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:46:51,526 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:47:01,527 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:47:11,539 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:47:21,549 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:47:31,561 [1] INFO     __main__: Hello Thoth ;)
2020-09-04 14:47:41,572 [1] INFO     __main__: Hello Thoth ;)
```

**Comment by fridex** [comment] 2020-09-04 15:05
> ```
> requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.moc.thoth-station.ninja/api/v1
> ```

It might be the moc deployment is down. The original issue should be fixed based on the logs.

CC @harshad16 @goern

**Comment by goern** [comment] 2020-09-11 07:27
@hashad16 ?

**Comment by goern** [comment] 2020-09-11 07:27
@harshad16
ping?

**Comment by btannous** [comment] 2020-10-06 16:38
any update guys?
@harshad16 @goern

**Comment by harshad16** [comment] 2020-10-06 18:08
hey,
apologize for the delay in response, we have got our cluster issues fixed.
users shouldn't face any more connection or any server support issue.

I have rerun the katacoda workshop to verify it. 
the Thoth recommendation advises are successfully being showcased.
![katacoda](https://user-images.githubusercontent.com/14028058/95242354-af720300-082c-11eb-9adb-9c4a74f1c185.png)

also the whole workflow is successfully being completed in the workshop.
![katacoda-1](https://user-images.githubusercontent.com/14028058/95242416-c31d6980-082c-11eb-9e76-3273ad90d4fa.png)

Please let us know if you are still facing any issues.
thanks for your patience and help in making our system and recommendations better.

**Comment by btannous** [comment] 2020-11-06 18:02
thank you!

**Closed by btannous** 2020-11-06 18:02 UTC
