### ISSUE TITLE
Service mesh - Circuit Breaker - misbehave function doesn't work as expected

### ISSUE THREAD

**Issue by tommeramber** [openshift-labs/learn-katacoda#825] opened 2020-07-07 07:59 UTC
In the service mesh learning path - Circuit breaker/Pool Ejection (step 4) it mentioned to run the following command:

`oc exec -it $(oc get pods|grep recommendation-v2|awk '{ print $1 }'|head -1) -c recommendation  /bin/bash ==> curl localhost:8080/misbehave`

It should make the recommendation endpoint in one of the pods misbehave, in order to show how the "pool ejection" functionality works.

I ran everything as instructed and when I try to test it I'm not getting the 503 response from the backend at all... 
`for i in {1..50}; do curl http://<exposed route> ; done`

**Comment by btannous** [comment] 2020-07-15 23:08
Doing some debugging here, it looks like the recommendation container is misbehaving as expected.

Preference and customer seem to handle the exception but apparently the http response from the customer fails causing a error with curl.
`curl: (18) transfer closed with 83 bytes remaining to read`

https://github.com/redhat-developer-demos/istio-tutorial/blob/katacoda/customer/java/springboot/src/main/java/com/redhat/developer/demos/customer/CustomerController.java

@lordofthejars curious if you have seen this?

**Comment by btannous** [comment] 2020-07-15 23:10
this is a duplicate of https://github.com/openshift-labs/learn-katacoda/issues/822
please use that issue.

Thank you for reporting!

**Closed by btannous** 2020-07-15 23:10 UTC
