### ISSUE TITLE
Istio learning series

### ISSUE THREAD

**Issue by koalabi** [openshift-labs/learn-katacoda#790] opened 2020-06-04 14:01 UTC
I have tried on several PC's: I cannot get started with the first session of learning. The download of the Service Mesh (istio) tar file takes forever and ends in timeout.

Is there anything special to be done?

Thanks in advance.

Kind regards

**Comment by btannous** [comment] 2020-06-09 19:21
Closing this as it is a duplicate of https://github.com/openshift-labs/learn-katacoda/issues/760 please refer / comment on that issue.
Thank you!

**Closed by btannous** 2020-06-09 19:21 UTC
