### ISSUE TITLE
Got 502 error when click on "Console" tab

### ISSUE THREAD

**Issue by csnckac** [openshift-labs/learn-katacoda#779] opened 2020-05-23 02:10 UTC
In "Getting Started with OpenShift for Developers"
Step 2 - Exploring The Web Console

When I click on "Consoles", I was redirected to https://console-openshift-console-2886795296-443-jago05.environments.katacoda.com/
and I got following error details:
This page isn’t workingconsole-openshift-console-2886795296-443-jago05.environments.katacoda.com is currently unable to handle this request.
HTTP ERROR 502

**Comment by btannous** [comment] 2020-05-26 15:36
This seems to work now, closing.  Please re-open if the issue is still happening on your end.

@BenHall for awareness

**Closed by btannous** 2020-05-26 15:36 UTC
