### ISSUE TITLE
indefinitely downloads 

### ISSUE THREAD

**Issue by ramakris** [openshift-labs/learn-katacoda#750] opened 2020-04-30 19:27 UTC
https://learn.openshift.com/servicemesh/1-introduction

**Comment by btannous** [comment] 2020-05-15 22:10
This is a duplicate of: https://github.com/openshift-labs/learn-katacoda/issues/760

Looks like issues with the init script not running, investigating it, but closing this to consolidate.  Please comment/track that one.  

Thank you!

**Closed by btannous** 2020-05-15 22:10 UTC

**Comment by btannous** [comment] 2020-05-15 22:13
see: https://github.com/openshift-labs/learn-katacoda/issues/760#issuecomment-625881686
