### ISSUE TITLE
Application Messaging with Openshift scenario - npm install fails

### ISSUE THREAD

**Issue by orange00** [openshift-labs/learn-katacoda#681] opened 2020-03-23 07:41 UTC
I get the following error in the scenario: https://learn.openshift.com/middleware/amq-getting-started-broker/

```
npm install
npm ERR! code EJSONPARSE
npm ERR! file /root/projects/amq-examples/amq-js-demo/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token v in JSON at position 0 while parsing near 'var container = requ...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-23T07_25_26_507Z-debug.log
$ npm install package.json
npm ERR! code EJSONPARSE
npm ERR! file /root/projects/amq-examples/amq-js-demo/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token v in JSON at position 0 while parsing near 'var container = requ...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-23T07_26_21_112Z-debug.log
```

**Comment by jankleinert** [comment] 2020-03-23 14:16
@orange00 I was not able to reproduce this issue. Is it still happening for you?

**Comment by jankleinert** [comment] 2020-04-23 14:36
Closing - please reopen if the issue persists.

**Closed by jankleinert** 2020-04-23 14:36 UTC
