### ISSUE TITLE
Unable to access URL to get a token for RH learning modules

### ISSUE THREAD

**Issue by mtbroekman** [openshift-labs/learn-katacoda#1134] opened 2021-06-02 12:57 UTC
When running the get started course on Redhat site https://learn.openshift.com/introduction/getting-started/
When I run the command oc login I get a failure message `You must obtain an API token by visiting https://oauth-openshift-2886795273-443-kota01.environments.katacoda.com/oauth/token/request` 

When I try access that URL in a browser it fails saying the site cannot be reached. This is the url it redirects to 
https://oauth-openshift.apps-crc.testing/oauth/authorize?client_id=openshift-browser-client&redirect_uri=https%3A%2F%2Foauth-openshift.apps-crc.testing%2Foauth%2Ftoken%2Fdisplay&response_type=code

**Comment by azaceta** [comment] 2021-06-04 14:31
Same issue here

**Comment by azaceta** [comment] 2021-06-04 14:39
Duplicate of #1114 
Documentation seems wrong

**Comment by ryanj** [comment] 2021-06-09 01:38
Thanks for the info - This should be fixed now

Feel free to reopen if you hit the same issue

**Closed by ryanj** 2021-06-09 01:38 UTC
Labels: Topic: OpenShift Basics
