### ISSUE TITLE
Cannot login to the OpenShift Tutorial

### ISSUE THREAD

**Issue by cohenjo92** [openshift-labs/learn-katacoda#1117] opened 2021-05-21 17:39 UTC
On step 2 of the tutorial "https://learn.openshift.com/introduction/cluster-access/," Logging into the Openshift cluster, I entered oc login on the embedded terminal and received the response: "You must obtain an API token by visiting https://oauth-openshift-2886795298-443-hazel05.environments.katacoda.com/oauth/token/request" instead of the expected prompt for username and password.

**Comment by azaceta** [comment] 2021-06-04 14:39
Duplicate of #1114

**Comment by ryanj** [comment] 2021-06-09 01:39
Thanks for the info - This should be fixed now

Feel free to reopen if you hit the same issue

**Closed by ryanj** 2021-06-09 01:39 UTC
Labels: Topic: OpenShift Basics
