### ISSUE TITLE
Node.js error

### ISSUE THREAD

**Issue by ComputerWolf** [openshift-labs/learn-katacoda#710] opened 2020-04-16 15:42 UTC
When attempting to run `npm run openshift` the following error occurs and prevents moving forward:

```
ERROR Argument error, options.body.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-configmap@1.0.0 openshift: `nodeshift --imageTag=12.x --strictSSL=false --tryServiceAccount=false --configLocation /openshift.local.config/master/admin.kubeconfig`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs-configmap@1.0.0 openshift script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-16T15_40_18_062Z-debug.log
```

**Comment by jankleinert** [comment] 2020-04-21 12:25
This is for https://learn.openshift.com/middleware/rhoar-getting-started-nodejs/

**Comment by jankleinert** [comment] 2020-04-21 12:30
I think this scenario needs to be updated to the newest version of nodeshift that was released last week to fix a bug. Will take a look.

**Comment by joellord** [comment] 2020-04-22 17:36
Unfortunately, I was unable to reproduce this. @ComputerWolf Could you confirm the scenario and at which step you are getting this error?

**Comment by jankleinert** [comment] 2020-04-22 17:43
This was fixed via https://github.com/openshift-katacoda/rhoar-getting-started/pull/30 yesterday. Forgot to update here

**Closed by jankleinert** 2020-04-22 17:43 UTC
