### ISSUE TITLE
User can freeze instance by opening files

### ISSUE THREAD

**Issue by kaovilai** [openshift-labs/learn-katacoda#470] opened 2019-05-28 20:22 UTC
From: https://learn.openshift.com/operatorframework/etcd-operator/
User can in the file browser click on large file like /root/tutorial/go/bin/operator-sdk and freezes the whole session requiring session restart.

**Comment by BenHall** [comment] 2019-09-04 11:43
Thanks for the feedback. Closing as a duplicate of #514 with a fix due soon for when this sometimes occurs.

**Closed by BenHall** 2019-09-04 11:43 UTC
