### ISSUE TITLE
API token URL not working

### ISSUE THREAD

**Issue by subhendudey** [openshift-labs/learn-katacoda#1125] opened 2021-05-28 07:56 UTC
As we trying to login there is a need to obtain a key
$ oc login
You must obtain an API token by visiting https://oauth-openshift-2886795279-443-hazel05.environments.katacoda.com/oauth/token/request

However the URL is not accessible and hence key could not be obtained. Tried login in web console and there also CLI command option (righthand top corner) is not working.

**Comment by azaceta** [comment] 2021-06-04 14:40
Duplicate of #1114 
Documentation seems wrong

**Comment by ryanj** [comment] 2021-06-09 01:37
Thanks for the info - This should be fixed now

Feel free to reopen if you hit the same issue

**Closed by ryanj** 2021-06-09 01:37 UTC
Labels: Topic: OpenShift Basics
