### ISSUE TITLE
Several Istio interactive labs fail to initialized

### ISSUE THREAD

**Issue by mexicanopelon** [openshift-labs/learn-katacoda#774] opened 2020-05-15 17:23 UTC
I have tried to start several interactive labs but they just hang during the initialization process.

**Comment by jankleinert** [comment] 2020-05-15 17:44
@btannous Can you take a look?

**Comment by mexicanopelon** [comment] 2020-05-15 19:43
Still having an issue.  They get stuck on this step:

$ echo "Downloading Istio..."
Downloading Istio...
$ until $(tar -tvf /root/installation/istio-1.0.5-linux.tar.gz &> /dev/null); do (echo -n .; sleep 2); done;
...........

**Comment by btannous** [comment] 2020-05-15 22:10
This is a duplicate of: https://github.com/openshift-labs/learn-katacoda/issues/760

Looks like issues with the init script not running, investigating it, but closing this to consolidate.  Please comment/track that one.  

Thank you!

**Comment by btannous** [comment] 2020-05-15 22:11
You can get around this issue by clicking on the + at the tab at the top, opening a new terminal and running:
`wget -c https://github.com/istio/istio/releases/download/1.0.5/istio-1.0.5-linux.tar.gz -P /root/installation`

**Closed by btannous** 2020-05-15 22:11 UTC
