### ISSUE TITLE
Keeps crashing while following the https://learn.openshift.com/operatorframework/go-operator-podset/ tutorial

### ISSUE THREAD

**Issue by swapnildaga17** [openshift-labs/learn-katacoda#514] opened 2019-07-25 06:20 UTC
![2019-07-25_1149](https://user-images.githubusercontent.com/16069560/61850720-994f7f80-aed2-11e9-9233-0e618f9b8b21.png)

**Comment by cameronkerrnz** [comment] 2019-08-22 09:31
I'm having the same issue currently.

This was in the 30 minutes or so prior to 2019-08-22T09:27:28+00:00. I'm in New Zealand (+12:00).

Perhaps a load issue, or perhaps due to this scenario may use more resources (eg. fetching go prerequisites). The fault does not trigger generally happen due to interaction, so possibly something under the hood, resourcing etc.

**Comment by BenHall** [comment] 2019-09-04 11:45
Thanks for the feedback. Closing as a duplicate of #517. The issue is related to client side memory usage and we're working on optimising the number of files shown in the editor to make it more lightweight.

**Closed by BenHall** 2019-09-04 11:45 UTC
