### ISSUE TITLE
Deploying Prometheus and Grafana on OpenShift

### ISSUE THREAD

**Issue by gerijani** [openshift-labs/learn-katacoda#805] opened 2020-06-21 11:36 UTC
Step 2 of 4 :

$ oc rollout latest dc/prometheus-demo -n pad-monitoring
Error from server (NotFound): deploymentconfigs.apps.openshift.io "prometheus-demo" not found

**Comment by jankleinert** [comment] 2020-06-22 18:50
Duplicate of https://github.com/openshift-labs/learn-katacoda/pull/802

**Closed by jankleinert** 2020-06-22 18:50 UTC
