### ISSUE TITLE
Unable to get the login command

### ISSUE THREAD

**Issue by RushinthJohn** [openshift-labs/learn-katacoda#1228] opened 2021-07-01 05:02 UTC
Hello,

After I create a cluster in [learn.openshift.com/playgrounds](https://learn.openshift.com/playgrounds/) and click on the **Copy Login Command** link it redirects to this URL `https://oauth-openshift.apps-crc.testing/oauth/authorize?client_id=openshift-browser-client&redirect_uri=https%3A%2F%2Foauth-openshift.apps-crc.testing%2Foauth%2Ftoken%2Fdisplay&response_type=code` whose domain can't be resolved. 

Please help with this issue.

Note: This issue occurs with both 4.5 and 4.7 Playgrounds

**Comment by RushinthJohn** [comment] 2021-07-01 05:05
Similar to https://github.com/openshift-labs/learn-katacoda/issues/1071

**Comment by RushinthJohn** [comment] 2021-07-01 05:09
https://dns.google.com/query?name=oauth-openshift.apps-crc.testing

**Comment by jdob** [comment] 2021-07-19 18:44
This is a side effect of how Katacoda works. Each instance of the playground is opened in a CodeReady Containers VM, which means you won't be able to access it from outside of the environment. 

Closing as not a bug.

**Closed by jdob** 2021-07-19 18:44 UTC
Labels: Bug
